---
# templates/configmaps.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  namespace: {{ .Values.global.namespace }}
data:
  MONGODB_INITDB_DATABASE: {{ .Values.mongodb.database }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: {{ .Values.global.namespace }}
data:
  REACT_APP_BACKEND_API: "http://backend-service.{{ .Values.global.namespace }}.svc.cluster.local:{{ .Values.backend.service.port }}/api"

