# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: imdb-clone-ingress
#   namespace: production
#   annotations:
#     nginx.ingress.kubernetes.io/ssl-redirect: "true"
#     nginx.ingress.kubernetes.io/use-regex: "true"
#     nginx.ingress.kubernetes.io/rewrite-target: /$1
#     nginx.ingress.kubernetes.io/proxy-body-size: "10m"
#     nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
#     nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
#     nginx.ingress.kubernetes.io/proxy-send-timeout: "30"
#     nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
#     cert-manager.io/cluster-issuer: "letsencrypt-prod"
# spec:
#   ingressClassName: nginx
#   tls:
#   - hosts:
#     - "prod-frontend.jayachandran.xyz"
#     - "prod-backend.jayachandran.xyz"
#     secretName: imdb-clone-tls
#   rules:
#   - host: "prod-frontend.jayachandran.xyz"
#     http:
#       paths:
#       - path: /(.*)
#         pathType: ImplementationSpecific
#         backend:
#           service:
#             name: frontend-service
#             port:
#               number: 3000
#   - host: "prod-backend.jayachandran.xyz"
#     http:
#       paths:
#       - path: /api/(.*)
#         pathType: ImplementationSpecific
#         backend:
#           service:
#             name: backend-service
#             port:
#               number: 5000
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: imdb-clone-ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - prod-frontend.jayachandran.xyz
    - prod-backend.jayachandran.xyz
    secretName: imdb-clone-tls
  rules:
  - host: prod-frontend.jayachandran.xyz
    http:
      paths:
      - path: /(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: frontend-service
            port:
              number: 3000
  - host: prod-backend.jayachandran.xyz
    http:
      paths:
      - path: /api/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: backend-service
            port:
              number: 5000
